#!/bin/bash
# =============================================================================
# Script 1: System Identity Report
# Author: SURYAION MUKHERJEE | Registration Number: 24BAC10009 
# Course: Open Source Software | Capstone Project
# Software Chosen: Git
# Description: Displays a welcome screen with system info and OSS license details
# =============================================================================

# --- Student and project variables ---
STUDENT_NAME="SURYAION MUKHERJEE"        # Storing student name for report output
REG_NUMBER="24BAC10009"                  # Storing registration number
SOFTWARE_CHOICE="Git"                    # Chosen open-source software project

# --- Gather system information using command substitution ---
KERNEL=$(uname -r)                       # Linux kernel version
# Read OS info, filter for the name, split at the '=', and remove quote marks
DISTRO=$(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '"')
USER_NAME=$(whoami)                      # Currently logged-in user
HOME_DIR=$HOME                           # Home directory of current user
UPTIME=$(uptime -p)                      # Human-readable uptime
CURRENT_DATE=$(date '+%A, %d %B %Y')    # Formatted current date
CURRENT_TIME=$(date '+%H:%M:%S')        # Current time

# --- Linux kernel license (always GPL v2) ---
OS_LICENSE="GNU General Public License version 2 (GPL v2)"

# --- Display the system identity report ---
# --- Output Generation ---
# Print the gathered variables in a formatted, human-readable layout
echo "=================================================================="
echo "          OPEN SOURCE SOFTWARE AUDIT — SYSTEM IDENTITY"
echo "=================================================================="
echo ""
echo "  Student   : $STUDENT_NAME"
echo "  Reg No    : $REG_NUMBER"
echo "  Software  : $SOFTWARE_CHOICE (GPL v2)"
echo ""
echo "=================================================================="
echo "                        SYSTEM INFORMATION"
echo "=================================================================="
echo ""
echo "  Distribution  : $DISTRO"
echo "  Kernel Version: $KERNEL"
echo "  Logged-in User: $USER_NAME"
echo "  Home Directory: $HOME_DIR"
echo "  System Uptime : $UPTIME"
echo "  Date          : $CURRENT_DATE"
echo "  Time          : $CURRENT_TIME"
echo ""
echo "=================================================================="
echo "                          OS LICENSE"
echo "=================================================================="
echo ""
echo "  This operating system (Linux) is distributed under:"
echo "  $OS_LICENSE"
echo ""
echo "  Git (our chosen software) is also licensed under GPL v2."
echo "  This means: you are free to use, study, modify, and"
echo "  redistribute it — as long as you keep those same freedoms"
echo "  intact for everyone downstream."
echo ""
echo "=================================================================="
echo "  Report generated by: $STUDENT_NAME | $(date '+%Y')"
echo "=================================================================="
